export type ClinicalTemplateField = {
  key: string;
  label: string;
  type?: "text" | "textarea" | "date" | "number" | "select";
  placeholder?: string;
  options?: Array<{ value: string; label: string }>;
};

export type ClinicalTemplateDef = {
  title: string;
  department: string;
  fields: ClinicalTemplateField[];
};

export const clinicalFormTemplates = {
  medical_record_cover: {
    title: "Medical Record Book Cover",
    department: "Reception",
    fields: [
      { key: "clinic_number", label: "Clinic Number" },
      { key: "name", label: "Name" },
      { key: "school_or_department", label: "School / Department" },
      { key: "computer_number", label: "Computer Number" },
      { key: "man_number", label: "Man Number" },
      { key: "patient_category", label: "Patient Category", placeholder: "Student, Staff, Staff Child, Spouse, External" },
      { key: "remarks", label: "Registration Notes", type: "textarea" },
    ],
  },
  general_client_information: {
    title: "General Client Information",
    department: "Reception",
    fields: [
      { key: "title", label: "Title" },
      { key: "surname", label: "Surname" },
      { key: "forenames", label: "Forenames" },
      { key: "dob", label: "Date of Birth", type: "date" },
      { key: "age", label: "Age", type: "number" },
      { key: "gender", label: "Gender" },
      { key: "nrc_or_passport", label: "NRC / Passport Number" },
      { key: "mobile_number", label: "Mobile Number" },
      { key: "residential_address", label: "Residential Address / Township", type: "textarea" },
      { key: "previous_illness", label: "Previous Illness or Operation", type: "textarea" },
      { key: "current_illness", label: "Current Illness / Medication", type: "textarea" },
      { key: "allergies", label: "Food or Drug Allergies", type: "textarea" },
      { key: "next_of_kin_name", label: "Next of Kin / Contact Name" },
      { key: "relationship", label: "Relationship" },
      { key: "next_of_kin_phone", label: "Emergency Contact Number" },
      { key: "registration_date", label: "Date of Registration", type: "date" },
      { key: "patient_category", label: "Patient Category" },
    ],
  },
  student_medical_exam: {
    title: "Student Medical Examination",
    department: "Clinical",
    fields: [
      { key: "surname", label: "Surname" },
      { key: "forenames", label: "Forenames" },
      { key: "computer_number", label: "Computer Number" },
      { key: "school", label: "School" },
      { key: "sex", label: "Sex" },
      { key: "age", label: "Age" },
      { key: "mobile_number", label: "Mobile Number" },
      { key: "height", label: "Height" },
      { key: "weight", label: "Weight" },
      { key: "temp", label: "Temperature" },
      { key: "bp", label: "Blood Pressure" },
      { key: "pulse", label: "Pulse Rate" },
      { key: "bmi", label: "BMI" },
      { key: "bmi_category", label: "BMI Category" },
      { key: "fitness_recommendation", label: "Fitness Recommendation" },
      { key: "urine", label: "Urine Findings", type: "textarea" },
      { key: "blood", label: "Blood Findings", type: "textarea" },
      { key: "vision", label: "Vision", type: "textarea" },
      { key: "diagnosis", label: "Diagnosis / Impression", type: "textarea" },
      { key: "diagnosis_code", label: "Diagnosis Code / National Code" },
      { key: "treatment_program", label: "Treatment Program / Clinic", placeholder: "ARV, TB, MCH, Hypertension, Diabetes..." },
      { key: "medications_given", label: "Medications Given", type: "textarea" },
      { key: "general_comments", label: "General Comments", type: "textarea" },
    ],
  },
  medical_fitness_certificate: {
    title: "Certificate of Medical Fitness",
    department: "Clinical",
    fields: [
      { key: "name", label: "Name" },
      { key: "school", label: "School" },
      { key: "comp_no", label: "Computer Number" },
      { key: "fitness_status", label: "Declared Fit/Unfit" },
      { key: "comments", label: "Comments", type: "textarea" },
      { key: "examiner_name", label: "Medical Examiner" },
      { key: "official_date", label: "Official Date", type: "date" },
    ],
  },
  laboratory_request: {
    title: "Laboratory Request Form",
    department: "Laboratory",
    fields: [
      { key: "client_id", label: "Client ID / Scheme Number" },
      { key: "clinical_details", label: "Clinical Details", type: "textarea" },
      { key: "requested_tests", label: "Requested Tests", type: "textarea", placeholder: "Parasitology, biochemistry, haematology, immunoserology, urine, stool, semen, microbiology, hormonal tests..." },
      { key: "haematology", label: "Haematology Requests", type: "textarea" },
      { key: "biochemistry", label: "Biochemistry Requests", type: "textarea" },
      { key: "immunoserology", label: "Immunoserology Requests", type: "textarea" },
      { key: "urine_tests", label: "Urine Tests", type: "textarea" },
      { key: "stool_tests", label: "Stool Tests", type: "textarea" },
      { key: "microbiology_tests", label: "Microbiology / Other Samples", type: "textarea" },
      { key: "semen_analysis", label: "Semen Analysis Requests", type: "textarea" },
      { key: "hormone_tests", label: "Hormone Tests", type: "textarea", placeholder: "Progesterone, Estradiol, Prolactin, LH, Testosterone, B-HCG" },
      { key: "requesting_officer", label: "Requesting Officer" },
    ],
  },
  outpatient_progress_notes: {
    title: "Outpatient Progress Notes",
    department: "Clinical",
    fields: [
      { key: "visit_date", label: "Visit Date", type: "date" },
      { key: "temp", label: "Temperature" },
      { key: "bp", label: "Blood Pressure" },
      { key: "pulse", label: "Pulse Rate" },
      { key: "resp_rate", label: "Respiratory Rate" },
      { key: "weight", label: "Weight" },
      { key: "history", label: "History", type: "textarea" },
      { key: "examination", label: "Examination", type: "textarea" },
      { key: "diagnosis", label: "Diagnosis", type: "textarea" },
      { key: "diagnosis_code", label: "Diagnosis Code / National Code" },
      { key: "assessment", label: "Assessment / Impression", type: "textarea" },
      { key: "investigations", label: "Investigations", type: "textarea" },
      { key: "treatment_program", label: "Treatment Program / Clinic", placeholder: "ARV, TB, Antenatal, Hypertension, Diabetes..." },
      { key: "medications_given", label: "Medications Given", type: "textarea" },
      { key: "treatment", label: "Treatment / Plan", type: "textarea" },
      { key: "review", label: "Review / Follow-up", type: "textarea" },
    ],
  },
  laboratory_slip: {
    title: "General Laboratory Request Slip",
    department: "Laboratory",
    fields: [
      { key: "lab_serial_no", label: "Lab Serial Number" },
      { key: "receipt_no", label: "Receipt Number" },
      { key: "specimens", label: "Specimens", type: "textarea" },
      { key: "tests_required", label: "Tests Required", type: "textarea" },
      { key: "requesting_officer", label: "Requesting Officer" },
      { key: "scheme_no", label: "Client ID / Scheme Number" },
    ],
  },
  laboratory_register_entry: {
    title: "Laboratory Register Entry",
    department: "Laboratory",
    fields: [
      { key: "date", label: "Date", type: "date" },
      { key: "lab_number", label: "Lab Number" },
      { key: "patient_name", label: "Patient Name" },
      { key: "requested_tests", label: "Tests Required", type: "textarea" },
      { key: "result_summary", label: "Result Summary", type: "textarea" },
      { key: "clinical_details", label: "Clinical Details", type: "textarea" },
      { key: "requested_by", label: "Requested By" },
      { key: "reported_by", label: "Reported By" },
    ],
  },
  consultation_referral: {
    title: "Medical Referral / Request for Consultation",
    department: "Clinical",
    fields: [
      { key: "hospital_or_clinic", label: "Hospital / Clinic" },
      { key: "patient_name", label: "Patient Name" },
      { key: "dob", label: "Date of Birth", type: "date" },
      { key: "admission_date", label: "Date of Visit / Admission", type: "date" },
      { key: "history_presenting_complaint", label: "History of Present Complaint", type: "textarea" },
      { key: "examination", label: "Examination Findings", type: "textarea" },
      { key: "clinic_summary", label: "Clinic Summary", type: "textarea" },
      { key: "investigations_done", label: "Investigations Done", type: "textarea" },
      { key: "diagnosis", label: "Diagnosis / Differential Diagnosis", type: "textarea" },
      { key: "diagnosis_code", label: "Diagnosis Code / National Code" },
      { key: "treatment_program", label: "Treatment Program / Clinic", placeholder: "ARV, TB, Mental Health, Oncology..." },
      { key: "medications_given", label: "Medications Given", type: "textarea" },
      { key: "management_plan", label: "Management Plan", type: "textarea" },
      { key: "reasons_for_referral", label: "Reasons for Referral", type: "textarea" },
      { key: "referred_by", label: "Referred By" },
    ],
  },
  eye_clinic_record: {
    title: "Eye Clinic Out-Patient Record",
    department: "Eye Clinic",
    fields: [
      { key: "reference_no", label: "Reference Number" },
      { key: "computer_no", label: "Computer Number" },
      { key: "phone_next_of_kin", label: "Phone / Next of Kin" },
      { key: "dept_school", label: "Department / School" },
      { key: "occupation", label: "Occupation" },
      { key: "class_of_patient", label: "Class of Patient (Paying / Free)" },
      { key: "clinical_eye_history", label: "Clinical Eye History", type: "textarea" },
      { key: "diagnosis", label: "Diagnosis", type: "textarea" },
      { key: "diagnosis_code", label: "Diagnosis Code / National Code" },
      { key: "treatment_program", label: "Treatment Program / Clinic" },
      { key: "medications_given", label: "Medications Given", type: "textarea" },
      { key: "treatment", label: "Treatment", type: "textarea" },
    ],
  },
  spectacles_prescription: {
    title: "Prescription Form for Spectacles",
    department: "Eye Clinic",
    fields: [
      { key: "telephone", label: "Telephone Number" },
      { key: "age", label: "Age", type: "number" },
      { key: "sex", label: "Sex" },
      { key: "right_eye", label: "Right Eye Prescription", type: "textarea", placeholder: "Sphere, Cylinder, Axis, Vision" },
      { key: "left_eye", label: "Left Eye Prescription", type: "textarea", placeholder: "Sphere, Cylinder, Axis, Vision" },
      { key: "pd", label: "PD" },
      { key: "remarks", label: "Remarks", type: "textarea" },
      { key: "prescriber_name", label: "Prescriber's Name" },
    ],
  },
  pharmacy_prescription: {
    title: "Prescription Form",
    department: "Pharmacy",
    fields: [
      { key: "clinic_number", label: "Clinic Number" },
      { key: "days_of_treatment", label: "Number of Days Treatment", type: "number" },
      { key: "items_prescribed", label: "Number of Items Prescribed", type: "number" },
      { key: "patient_age", label: "Patient Age" },
      { key: "treatment_program", label: "Treatment Program / Clinic", placeholder: "ARV, TB, Diabetes, Hypertension..." },
      { key: "generic_names", label: "Generic Name(s) Only", type: "textarea" },
      { key: "prescriber_name", label: "Prescriber Name" },
      { key: "prescriber_number", label: "Prescriber's Number" },
      { key: "department_stamp", label: "Department Stamp / Notes" },
    ],
  },
  sick_list_admission: {
    title: "Certificate of Admission to Sick List",
    department: "Inpatient",
    fields: [
      { key: "file_no", label: "File Number" },
      { key: "date_of_admission", label: "Date of Admission", type: "date" },
      { key: "date_of_discharge", label: "Date of Discharge", type: "date" },
      { key: "remarks", label: "Remarks", type: "textarea" },
      { key: "review_date", label: "Review Date", type: "date" },
      { key: "review_time", label: "Review Time" },
      { key: "signed_by", label: "Signed By" },
    ],
  },
  inpatient_drug_sheet: {
    title: "In Patient Drug Sheet",
    department: "Inpatient",
    fields: [
      { key: "gender", label: "Gender" },
      { key: "age", label: "Age" },
      { key: "weight", label: "Weight" },
      { key: "ward", label: "Ward" },
      { key: "bed_no", label: "Bed Number" },
      { key: "clinic_no", label: "Clinic Number" },
      { key: "treatment_program", label: "Treatment Program / Clinic" },
      { key: "drug_orders", label: "Drug Orders", type: "textarea", placeholder: "Date commenced, drug, dosage, route, ordered by, time, supplied by..." },
      { key: "other_prescriptions", label: "Other Prescriptions / Treatment", type: "textarea" },
    ],
  },
} satisfies Record<string, ClinicalTemplateDef>;

export type ClinicalTemplateKey = keyof typeof clinicalFormTemplates;
